import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Provider } from "@/store/Provider";
import {
  ClerkProvider,
  UserButton
} from '@clerk/nextjs'

const poppins = Poppins({ subsets: ["latin"], weight: "400" });
export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body
					className={`${poppins.className} antialiased min-h-screen bg-[#f5f5f5]`}
				>
					<Provider>
						{children}
						<div className="absolute top-4 right-4">
							<UserButton />
						</div>
					</Provider>
					
				</body>
			</html>
		</ClerkProvider>
	);
}
